ROBOT_TYPE: 'h1-2'
# ROBOT_SCENE: "../roboverse/data/robots/h1_2/h1_2_27dof_with_hand.xml" # Robot scene, for Sim2Sim
ROBOT_SCENE: "../roboverse/data/robots/h1_2/motion_tracking_h1_2_27dof.xml" # Robot scene, for Sim2Sim

### REAL
# DOMAIN_ID: 0 # Domain id
# # Interface
# INTERFACE: "en0" # Yuanhang: in simulation, lo0 for mac, lo for linux

## SIM
DOMAIN_ID: 1 # Domain id
# Interface
INTERFACE: "lo" # Yuanhang: in simulation, lo0 for mac, lo for linux

PRINT_SCENE_INFORMATION: True # Print link, joint and sensors information of robot
ENABLE_ELASTIC_BAND: True # Virtual spring band, used for lifting h1

SIMULATE_DT: 0.001  # Need to be larger than the runtime of viewer.sync()

MOTOR2JOINT: [0, 1, 2, 3, 4, 5,
              6, 7, 8, 9, 10, 11,
              12, 
              13, 14, 15, 16, 17, 18, 19,
              20, 21, 22, 23, 24, 25, 26]
            
JOINT2MOTOR: [0, 1, 2, 3, 4, 5,
              6, 7, 8, 9, 10, 11,
              12, 
              13, 14, 15, 16, 17, 18, 19,
              20, 21, 22, 23, 24, 25, 26]
            

UNITREE_LEGGED_CONST:
  HIGHLEVEL: 0xEE
  LOWLEVEL: 0xFF
  TRIGERLEVEL: 0xF0
  PosStopF: 2146000000.0
  VelStopF: 16000.0
  MODE_MACHINE: 6
  MODE_PR:  0

JOINT_KP: [
    200, 200, 200, 300, 60, 40,
    200, 200, 200, 300, 60, 40,
    600, 
    80, 80, 40, 60, 40, 40, 40,
    80, 80, 40, 60, 40, 40, 40
]

JOINT_KD: [
   5.0, 5.0, 5.0, 7.5, 1.0, 0.3,
   5.0, 5.0, 5.0, 7.5, 1.0, 0.3,
   15.0, 
   2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0,
   2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0,
]

WeakMotorJointIndex:
  left_hip_yaw_joint: 0
  left_hip_roll_joint: 1
  left_hip_pitch_joint: 2
  left_knee_joint: 3
  left_ankle_pitch_joint: 4
  left_ankle_roll_joint: 5
  right_hip_yaw_joint: 6
  right_hip_roll_joint: 7
  right_hip_pitch_joint: 8
  right_knee_joint: 9
  right_ankle_pitch_joint: 10
  right_ankle_roll_joint: 11
  waist_yaw_joint : 12
  left_shoulder_pitch_joint: 13
  left_shoulder_roll_joint: 14
  left_shoulder_yaw_joint: 15
  left_elbow_joint: 16
  left_wrist_roll_joint: 17
  left_wrist_pitch_joint: 18
  left_wrist_yaw_joint: 19
  right_shoulder_pitch_joint: 20
  right_shoulder_roll_joint: 21
  right_shoulder_yaw_joint: 22
  right_elbow_joint: 23
  right_wrist_roll_joint: 24
  right_wrist_pitch_joint: 25
  right_wrist_yaw_joint: 26

NUM_MOTOR: 27
NUM_JOINTS: 27

DEFAULT_DOF_ANGLES: [
    0.0,  # left_hip_yaw_joint
    -0.6, # left_hip_pitch_joint
    0.0,  # left_hip_roll_joint
    1.2,  # left_knee_joint
    -0.6, # left_ankle_pitch_joint
    0.0,  # left_ankle_roll_joint

   
    0.0,  # right_hip_yaw_joint
    -0.6, # right_hip_pitch_joint
    0.0,  # right_hip_roll_joint
    1.2,  # right_knee_joint
    -0.6, # right_ankle_pitch_joint
    0.0,  # right_ankle_roll_joint

    0.0,  # waist_yaw_joint

    0.4,  # left_shoulder_pitch_joint
    0.0,  # left_shoulder_roll_joint
    0.0,  # left_shoulder_yaw_joint
    0.3,  # left_elbow_joint
    0.0,  # left_wrist_roll_joint
    0.0,  # left_wrist_pitch_joint
    0.0,  # left_wrist_yaw_joint

    0.4,  # right_shoulder_pitch_joint
    0.0,  # right_shoulder_roll_joint
    0.0,  # right_shoulder_yaw_joint
    0.3,  # right_elbow_joint
    0.0,  # right_wrist_roll_joint
    0.0,  # right_wrist_pitch_joint
    0.0   # right_wrist_yaw_joint
]
