# @package _global_

defaults:
  - g1/g1_29dof_with_rubberhand

robot:
  num_bodies: 30
  body_names: ['pelvis', 
                 'left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link', 
                 'right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link', 
                 'waist_yaw_link', 'waist_roll_link', 'torso_link',
                 'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link',
                 'left_wrist_roll_link', 'left_wrist_pitch_link', 'left_wrist_yaw_link',
                 'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link',
                 'right_wrist_roll_link', 'right_wrist_pitch_link', 'right_wrist_yaw_link']
          
  asset:
    robot_type: g1_29dof_with_hand_rev_1_0_fixedhand