# @package _global_

defaults:
  - robot_base

robot:
  # Observation parameters
  fix_root_link: True # TEST: fix base link to world

  num_bodies: 30
  dof_obs_size: 29
  actions_dim: 29
  lower_body_actions_dim: 0
  upper_body_actions_dim: 29
  hand_contact_body_size: 8
  policy_obs_dim: -1
  critic_obs_dim: -1
  knee_name: ""
  key_bodies: []
  contact_bodies: []
  foot_name: ""
  has_torso: True
  torso_name: "torso_link"
  has_upper_body_dof: True
  dof_names: [ 'waist_yaw_joint', # waist
              'left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint', 'left_elbow_joint', # left shoulder + elbow
              'left_wrist_roll_joint', 'left_wrist_pitch_joint', 'left_wrist_yaw_joint', # left wrist
              'right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint',  # right shoulder + elbow
              'right_wrist_roll_joint', 'right_wrist_pitch_joint', 'right_wrist_yaw_joint', # right wrist
              'left_hand_thumb_0_joint', 'left_hand_thumb_1_joint', 'left_hand_thumb_2_joint', # left hand
              'left_hand_middle_0_joint', 'left_hand_middle_1_joint',  # left hand
               'left_hand_index_0_joint', 'left_hand_index_1_joint', # left hand
               'right_hand_thumb_0_joint', 'right_hand_thumb_1_joint', 'right_hand_thumb_2_joint', # right hand
               'right_hand_middle_0_joint', 'right_hand_middle_1_joint',  # right hand
                'right_hand_index_0_joint', 'right_hand_index_1_joint' # right hand
  ]
  upper_dof_names: ['left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint', 'left_elbow_joint', 
                    'left_wrist_roll_joint', 'left_wrist_pitch_joint', 'left_wrist_yaw_joint',
                    'right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint', 
                    'right_wrist_roll_joint', 'right_wrist_pitch_joint', 'right_wrist_yaw_joint',
                    'left_hand_thumb_0_joint', 'left_hand_thumb_1_joint', 'left_hand_thumb_2_joint',
                    'left_hand_middle_0_joint', 'left_hand_middle_1_joint',
                     'left_hand_index_0_joint', 'left_hand_index_1_joint',
                     'right_hand_thumb_0_joint', 'right_hand_thumb_1_joint', 'right_hand_thumb_2_joint',
                     'right_hand_middle_0_joint', 'right_hand_middle_1_joint',
                      'right_hand_index_0_joint', 'right_hand_index_1_joint'
                    ]
  lower_dof_names: []
  upper_left_arm_dof_names: ['left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint', 'left_elbow_joint']
  upper_right_arm_dof_names: ['right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint']
  waist_dof_names: ['waist_yaw_joint'] # NOTE: waist_roll_joint and waist_pitch_joint are fixed
  dof_pos_lower_limit_list: [
    -2.618,  # Waist (yaw only)
    -3.0892, -1.5882, -2.618, -1.0472, -1.9722, -1.6144, -1.6144,  # Left Arm
    -3.0892, -2.2515, -2.618, -1.0472, -1.9722, -1.6144, -1.6144,  # Right Arm
    -1.0472, -0.7243, 0, -1.5708, -1.7453, -1.5708, -1.7453,  # Left Hand
    -1.0472, -1.0472, -1.7453, 0, 0, 0, 0  # Right Hand
]
  dof_pos_upper_limit_list: [
    2.618,  # Waist (yaw only)
    2.6704, 2.2515, 2.618, 2.0944, 1.9722, 1.6144, 1.6144,  # Left Arm
    2.6704, 1.5882, 2.618, 2.0944, 1.9722, 1.6144, 1.6144,  # Right Arm
    1.0472, 1.0472, 1.7453, 0, 0, 0, 0,  # Left Hand
    1.0472, 0.7243, 0, 1.5708, 1.7453, 1.5708, 1.7453  # Right Hand
]
  dof_vel_limit_list: [32.0,  # Waist (yaw only)
                       37.0, 37.0, 37.0, 37.0,  # left shoulder + elbow
                       37.0, 22.0, 22.0, # left wrist
                       37.0, 37.0, 37.0, 37.0,  #  right shoulder + elbow
                       37.0, 22.0, 22.0, # right wrist
                       6.857, 12, 12, 12, 12, 12, 12,  # left hand
                       6.857, 12, 12, 12, 12, 12, 12,  # right hand
                       ]
  dof_effort_limit_list: [88.0,  # Waist (yaw only)
                          25.0, 25.0, 25.0, 25.0, 
                          25.0, 5.0, 5.0,
                          25.0, 25.0, 25.0, 25.0, 
                          25.0, 5.0, 5.0, 
                          2.45, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4,  # left hand
                          2.45, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4,  # right hand
                          ]
  
  # only apply for isaacsim
  dof_armature_list: [0.15,  # Waist (yaw only)
                      0.15, 0.15, 0.15, 0.15,
                      0.15, 0.15, 0.15,
                      0.15, 0.15, 0.15, 0.15,
                      0.15, 0.15, 0.15,
                      0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08,  # left hand
                      0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08]  # right hand
  # only apply for isaacsim
  dof_joint_friction_list: [0.03,  # Waist (yaw only)
                            0.03, 0.03, 0.03, 0.03,
                            0.03, 0.03, 0.03,
                            0.03, 0.03, 0.03, 0.03,
                            0.03, 0.03, 0.03,
                            0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,  # left hand
                            0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]  # right hand


  body_names: ['pelvis', 
                'waist_yaw_link', 'torso_link',
                'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link', 
                'left_wrist_roll_link', 'left_wrist_pitch_link', 'left_wrist_yaw_link',
                'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link', 
                'right_wrist_roll_link', 'right_wrist_pitch_link', 'right_wrist_yaw_link',
                'left_hand_thumb_0_link', 'left_hand_thumb_1_link', 'left_hand_thumb_2_link', # left hand
                'left_hand_middle_0_link', 'left_hand_middle_1_link',  # left hand
                 'left_hand_index_0_link', 'left_hand_index_1_link', # left hand
                 'right_hand_thumb_0_link', 'right_hand_thumb_1_link', 'right_hand_thumb_2_link', # right hand
                 'right_hand_middle_0_link', 'right_hand_middle_1_link',  # right hand
                  'right_hand_index_0_link', 'right_hand_index_1_link' # right hand
                ]


  terminate_after_contacts_on : ["pelvis", "shoulder"]
  penalize_contacts_on: ["pelvis", "shoulder"]
  init_state:
    pos: [0.0, 0.0, 0.8] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
    lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
    default_joint_angles: # = target angles [rad] when action = 0.0
      waist_yaw_joint : 0.
      left_shoulder_pitch_joint: 0.
      left_shoulder_roll_joint: 0.
      left_shoulder_yaw_joint: 0.
      left_elbow_joint: 0.
      left_wrist_roll_joint: 1.57
      left_wrist_pitch_joint: 0.
      left_wrist_yaw_joint: 0.
      right_shoulder_pitch_joint: 0.
      right_shoulder_roll_joint: 0.
      right_shoulder_yaw_joint: 0.
      right_elbow_joint: 0.
      right_wrist_roll_joint: 0.
      right_wrist_pitch_joint: 0.
      right_wrist_yaw_joint: 0.
      left_hand_thumb_0_joint: 0.
      left_hand_thumb_1_joint: 0.
      left_hand_thumb_2_joint: 0.
      left_hand_middle_0_joint: 0.
      left_hand_middle_1_joint: 0.
      left_hand_index_0_joint: 0.
      left_hand_index_1_joint: 0.
      right_hand_thumb_0_joint: 0.
      right_hand_thumb_1_joint: 0.
      right_hand_thumb_2_joint: 0.
      right_hand_middle_0_joint: 0.
      right_hand_middle_1_joint: 0.
      right_hand_index_0_joint: 0.
      right_hand_index_1_joint: 0.


  randomize_link_body_names: [
    'pelvis'
  ]

  motion:
    lower_body_link:
      - "pelvis"
      - "waist_yaw_link"
      - "torso_link"

    upper_body_link:
      - "left_shoulder_pitch_link"
      - "left_shoulder_roll_link"
      - "left_shoulder_yaw_link"
      - "left_elbow_link"
      - "right_shoulder_pitch_link"
      - "right_shoulder_roll_link"
      - "right_shoulder_yaw_link"
      - "right_elbow_link"
      - "left_hand_link"
      - "right_hand_link"

    pelvis_link: "pelvis"
    base_link: "torso_link"
    hips_link: []
    fingertip_link:
      - "left_hand_thumb_2_link"
      - "left_hand_index_1_link"
      - "left_hand_middle_1_link"
      - "right_hand_thumb_2_link"
      - "right_hand_index_1_link"
      - "right_hand_middle_1_link"

  control:
    control_type: P
    # PD Drive parameters:
    stiffness: # [N*m/rad]
      waist_yaw: 400
      shoulder_pitch: 90
      shoulder_roll: 60
      shoulder_yaw: 20
      elbow: 60
      wrist_roll: 4.0
      wrist_pitch: 4.0
      wrist_yaw: 4.0
      hand: 1.0
  # /todo

    damping: # [N*m/rad]  # [N*m*s/rad]
      waist_yaw: 5.0
      shoulder_pitch: 2.0
      shoulder_roll: 1.0
      shoulder_yaw: 0.4
      elbow: 1.0
      wrist_roll: 0.2
      wrist_pitch: 0.2
      wrist_yaw: 0.2
      hand: 0.5
  # /todo
    # action scale: target angle = actionScale * action + defaultAngle
    action_scale: 0.25
      # .*_hip_(pitch).*: 0.25
      # .*_hip_(roll|yaw).*: 0.25
      # .*_knee_.*: 0.5
      # .*_ankle_.*: 0.25
      # waist_.*: 0.25
      # .*_shoulder_.*: 0.25
      # .*_elbow_.*: 0.1
      # .*_wrist_.*: 0.1
      # .*_hand_.*: 0.1

    # todo: different scale for different joints
    action_clip_value: 100.0
    clip_torques: True

  asset:
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.001 # isaacgym armature is set by this
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    urdf_file: "g1/${robot.asset.robot_type}.urdf"
    usd_file: "g1/${robot.asset.robot_type}.usd"
    xml_file: "g1/${robot.asset.robot_type}.xml"
    robot_type: g1_fix_lower
    self_collisions: 1 # 1 to disable, 0 to enable self collisions
    default_dof_drive_mode: 3