ROBOT_TYPE: 't1_29dof' # Robot name, "t1_23dof", "g1_29dof", "go2", "b2", "b2w", "h1", "go2w"
ROBOT_SCENE: "../humanoidverse/data/robots/t1/scene_t1_29dof.xml" # Robot scene, for Sim2Sim
ASSET_ROOT: "../humanoidverse/data/robots/t1" # Robot Asset Root
ASSET_FILE: "../humanoidverse/data/robots/t1/t1_29dof.urdf" # Robot Asset File"

# Model path for the trained policy
model_path: "models/falcon/t1_29dof/model_9999.onnx"

# Yuanhang
SDK_TYPE: "booster" # SDK type, "unitree", "booster"
MOTOR_TYPE: "serial" # Motor type, "serial" or "parallel"
# NET: 192.168.10.10
NET: 127.0.0.1

## SIM
DOMAIN_ID: 0 # Domain id
INTERFACE: "lo" # in simulation, lo0 for mac, lo for linux

FREE_BASE: False # True

PRINT_SCENE_INFORMATION: True # Print link, joint and sensors information of robot
ENABLE_ELASTIC_BAND: True # Virtual spring band, used for lifting h1

SIMULATE_DT: 0.005  # Need to be larger than the runtime of viewer.sync()
VIEWER_DT: 0.02  # Viewer update time
USE_SENSOR: False

USE_JOYSTICK: 0 # Simulate Unitree WirelessController using a gamepad (0: disable, 1: enable)
JOYSTICK_TYPE: "xbox" # support "xbox" and "switch" gamepad layout
JOYSTICK_DEVICE: 0 # Joystick number

VISUALIZE_PIN: False
VISUALIZE_FORCES: False

residual_upper_body_action: True # Whether to use residual upper body action for balancing
use_upper_body_controller: False # Whether to use upper body controller

DESIRED_BASE_HEIGHT: 0.635 # Desired base height

BASE_BODY_NAME: "Trunk" # Base body name
BAND_ATTACHED_LINK: "Trunk" # Band attached link name

MOTOR2JOINT: [0, 1, 
              2, 3, 4, 5, 6, 7, 8,
              9, 10, 11, 12, 13, 14, 15, 
              16, 
              17, 18, 19, 20, 21, 22,
              23, 24, 25, 26, 27, 28]
            
JOINT2MOTOR: [0, 1, 
              2, 3, 4, 5, 6, 7, 8,
              9, 10, 11, 12, 13, 14, 15,
              16,
              17, 18, 19, 20, 21, 22,
              23, 24, 25, 26, 27, 28]
            
UNITREE_LEGGED_CONST:
  HIGHLEVEL: 0xEE
  LOWLEVEL: 0xFF
  TRIGERLEVEL: 0xF0
  PosStopF: 2146000000.0
  VelStopF: 16000.0
  MODE_MACHINE: 5
  MODE_PR:  0

JOINT_KP: [
  5, 5, 
  20, 20, 20, 20, 20, 20, 20,
  20, 20, 20, 20, 20, 20, 20,
  200,
  200, 200, 200, 200, 50, 50,
  200, 200, 200, 200, 50, 50,
]

JOINT_KD: [
  0.5, 0.5, 
  0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
  0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
  5.0,
  5.0, 5.0, 5.0, 5.0, 3.0, 3.0,
  5.0, 5.0, 5.0, 5.0, 3.0, 3.0,
]

MOTOR_KP: [
  5, 5, 
  20, 20, 20, 20, 20, 20, 20,
  20, 20, 20, 20, 20, 20, 20,
  200,
  200, 200, 200, 200, 50, 50,
  200, 200, 200, 200, 50, 50,
]

MOTOR_KD: [
  0.5, 0.5, 
  0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
  0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
  5.0,
  5.0, 5.0, 5.0, 5.0, 3.0, 3.0,
  5.0, 5.0, 5.0, 5.0, 3.0, 3.0,
]

dof_names: ['AAHead_yaw', 'Head_pitch',
            'Left_Shoulder_Pitch', 'Left_Shoulder_Roll', 'Left_Elbow_Pitch', 'Left_Elbow_Yaw', 'Left_Wrist_Pitch', 'Left_Wrist_Yaw', 'Left_Hand_Roll',
            'Right_Shoulder_Pitch', 'Right_Shoulder_Roll', 'Right_Elbow_Pitch', 'Right_Elbow_Yaw', 'Right_Wrist_Pitch', 'Right_Wrist_Yaw', 'Right_Hand_Roll',
            'Waist',
            'Left_Hip_Pitch', 'Left_Hip_Roll', 'Left_Hip_Yaw', 'Left_Knee_Pitch', 'Left_Ankle_Pitch', 'Left_Ankle_Roll',
            'Right_Hip_Pitch', 'Right_Hip_Roll', 'Right_Hip_Yaw', 'Right_Knee_Pitch', 'Right_Ankle_Pitch', 'Right_Ankle_Roll']
dof_names_upper_body: ['AAHead_yaw', 'Head_pitch',
                       'Left_Shoulder_Pitch', 'Left_Shoulder_Roll', 'Left_Elbow_Pitch', 'Left_Elbow_Yaw', 'Left_Wrist_Pitch', 'Left_Wrist_Yaw', 'Left_Hand_Roll',
                       'Right_Shoulder_Pitch', 'Right_Shoulder_Roll', 'Right_Elbow_Pitch', 'Right_Elbow_Yaw', 'Right_Wrist_Pitch', 'Right_Wrist_Yaw', 'Right_Hand_Roll'
                       ]
dof_names_lower_body: ['Waist',
                       'Left_Hip_Pitch', 'Left_Hip_Roll', 'Left_Hip_Yaw', 'Left_Knee_Pitch', 'Left_Ankle_Pitch', 'Left_Ankle_Roll',
                       'Right_Hip_Pitch', 'Right_Hip_Roll', 'Right_Hip_Yaw', 'Right_Knee_Pitch', 'Right_Ankle_Pitch', 'Right_Ankle_Roll'
                       ]
dof_names_parallel_mech: ['Left_Ankle_Pitch', 'Left_Ankle_Roll', 'Right_Ankle_Pitch', 'Right_Ankle_Roll']
WeakMotorJointIndex:
  AAHead_yaw: 0
  Head_pitch: 1
  Left_Shoulder_Pitch: 2
  Left_Shoulder_Roll: 3
  Left_Elbow_Pitch: 4
  Left_Elbow_Yaw: 5
  Left_Wrist_Pitch: 6
  Left_Wrist_Yaw: 7
  Left_Hand_Roll: 8
  Right_Shoulder_Pitch: 9
  Right_Shoulder_Roll: 10
  Right_Elbow_Pitch: 11
  Right_Elbow_Yaw: 12
  Right_Wrist_Pitch: 13
  Right_Wrist_Yaw: 14
  Right_Hand_Roll: 15
  Waist: 16
  Left_Hip_Pitch: 17
  Left_Hip_Roll: 18
  Left_Hip_Yaw: 19
  Left_Knee_Pitch: 20
  Left_Ankle_Pitch: 21
  Left_Ankle_Roll: 22
  Right_Hip_Pitch: 23
  Right_Hip_Roll: 24
  Right_Hip_Yaw: 25
  Right_Knee_Pitch: 26
  Right_Ankle_Pitch: 27
  Right_Ankle_Roll: 28

NUM_MOTORS: 29
NUM_JOINTS: 29
NUM_UPPER_BODY_JOINTS: 16

    # default_joint_angles: # = target angles [rad] when action = 0.0
    #   AAHead_yaw: 0.
    #   Head_pitch: 0.
    #   Left_Shoulder_Pitch: 0.2
    #   Left_Shoulder_Roll: -1.35
    #   Left_Elbow_Pitch: 0.
    #   Left_Elbow_Yaw: -0.5
    #   Right_Shoulder_Pitch: 0.2
    #   Right_Shoulder_Roll: 1.35
    #   Right_Elbow_Pitch: 0.
    #   Right_Elbow_Yaw: 0.5
    #   Waist: 0.
    #   Left_Hip_Pitch: -0.2
    #   Left_Hip_Roll: 0.
    #   Left_Hip_Yaw: 0. 
    #   Left_Knee_Pitch: 0.4
    #   Left_Ankle_Pitch: -0.25
    #   Left_Ankle_Roll: 0.
    #   Right_Hip_Pitch: -0.2
    #   Right_Hip_Roll: 0. 
    #   Right_Hip_Yaw: 0.
    #   Right_Knee_Pitch: 0.4
    #   Right_Ankle_Pitch: -0.25
    #   Right_Ankle_Roll: 0.
DEFAULT_DOF_ANGLES: [
    0.0,  # AAHead_yaw
    0.0,  # Head_pitch
    0.2,  # Left_Shoulder_Pitch
    -1.35,  # Left_Shoulder_Roll
    0.0,  # Left_Elbow_Pitch
    -0.5,  # Left_Elbow_Yaw
    0.0,  # Left_Wrist_Pitch
    0.0,  # Left_Wrist_Yaw
    0.0,  # Left_Hand_Roll
    0.2,  # Right_Shoulder_Pitch
    1.35,  # Right_Shoulder_Roll
    0.0,  # Right_Elbow_Pitch
    0.5,  # Right_Elbow_Yaw
    0.0,  # Right_Wrist_Pitch
    0.0,  # Right_Wrist_Yaw
    0.0,  # Right_Hand_Roll
    0.0,  # Waist
    -0.2,  # Left_Hip_Pitch
    0.0,  # Left_Hip_Roll
    0.0,  # Left_Hip_Yaw
    0.4,  # Left_Knee_Pitch
    -0.25, # Left_Ankle_Pitch
    0.0,  # Left_Ankle_Roll
    -0.2,  # Right_Hip_Pitch
    0.0,  # Right_Hip_Roll
    0.0,  # Right_Hip_Yaw
    0.4,  # Right_Knee_Pitch
    -0.25, # Right_Ankle_Pitch
    0.0,  # Right_Ankle_Roll
]

DEFAULT_MOTOR_ANGLES: [
    0.0,  # AAHead_yaw
    0.0,  # Head_pitch
    0.2,  # Left_Shoulder_Pitch
    -1.35,  # Left_Shoulder_Roll
    0.0,  # Left_Elbow_Pitch
    -0.5,  # Left_Elbow_Yaw
    0.0,  # Left_Wrist_Pitch
    0.0,  # Left_Wrist_Yaw
    0.0,  # Left_Hand_Roll
    0.2,  # Right_Shoulder_Pitch
    1.35,  # Right_Shoulder_Roll
    0.0,  # Right_Elbow_Pitch
    0.5,  # Right_Elbow_Yaw
    0.0,  # Right_Wrist_Pitch
    0.0,  # Right_Wrist_Yaw
    0.0,  # Right_Hand_Roll
    0.0,  # Waist
    -0.2,  # Left_Hip_Pitch
    0.0,  # Left_Hip_Roll
    0.0,  # Left_Hip_Yaw
    0.4,  # Left_Knee_Pitch
    -0.25, # Left_Ankle_Pitch
    0.0,  # Left_Ankle_Roll
    -0.2,  # Right_Hip_Pitch
    0.0,  # Right_Hip_Roll
    0.0,  # Right_Hip_Yaw
    0.4,  # Right_Knee_Pitch
    -0.25, # Right_Ankle_Pitch
    0.0,  # Right_Ankle_Roll
]

motor_pos_lower_limit_list: [-1.57, -0.35,
                             -3.31, -1.74, -2.27, -2.27, -2.27, -2.27, -2.27,
                             -3.31, -1.57, -2.27, -2.27, -2.27, -2.27, -2.27,
                             -1.57,
                             -1.8, -0.3, -1, 0, -0.87, -0.44, 
                             -1.8, -1.57, -1, 0, -0.87, -0.44]
motor_pos_upper_limit_list: [1.57, 1.22,
                             1.22, 1.57, 2.27, 2.27, 2.27, 2.27, 2.27,
                             1.22, 1.74, 2.27, 2.27, 2.27, 2.27, 2.27,
                             1.57,
                             1.57, 1.57, 1, 2.34, 0.35, 0.44,
                             1.57, 0.3, 1, 2.34, 0.35, 0.44]
motor_vel_limit_list: [12.56, 12.56,
                       18.84, 18.84, 18.84, 18.84, 18.84, 18.84, 18.84,
                       18.84, 18.84, 18.84, 18.84, 18.84, 18.84, 18.84,
                       10.88,
                       12.5, 10.9, 10.9, 11.7, 18.8, 12.4,
                       12.5, 10.9, 10.9, 11.7, 18.8, 12.4,]
motor_effort_limit_list: [7, 7,
                          18, 18, 18, 18, 18, 18, 18,
                          18, 18, 18, 18, 18, 18, 18,
                          30,
                          45, 30, 30, 60, 12, 12,
                          45, 30, 30, 60, 12, 12,]
obs_dict: {
  actor_obs: [
    base_ang_vel,
    projected_gravity,
    command_lin_vel,
    command_ang_vel,
    command_stand,
    command_base_height,
    command_waist_dofs,
    ref_upper_dof_pos,
    dof_pos,
    dof_vel,
    actions,
  ],
}
history_length_dict: {
  actor_obs: 5,
}
obs_dims: {
            base_lin_vel: 3,
            base_ang_vel: 3,
            projected_gravity: 3,
            command_lin_vel: 2,
            command_ang_vel: 1,
            command_stand: 1,
            command_base_height: 1,
            command_waist_dofs: 3,
            ref_upper_dof_pos: 16, # upper body actions
            dof_pos: 29,
            dof_vel: 29,
            actions: 29, # lower body actions
            phase_time: 1,
          }
obs_scales: {
    base_lin_vel: 1.0,
    base_ang_vel: 1.0,
    projected_gravity: 1.0,
    command_lin_vel: 1.0,
    command_ang_vel: 1.0,
    command_stand: 1.0,
    command_waist_dofs: 1.0,
    command_base_height: 2.0,
    ref_upper_dof_pos: 1.0,
    dof_pos: 1.0,
    dof_vel: 0.1,
    actions: 1.0,
    left_ee_apply_force: 0.1,
    right_ee_apply_force: 0.1,
    history_actor: 1.0,
  }

prepare:
  stiffness: [
    5., 5.,
    40., 50., 20., 10., 10., 10., 10.,
    40., 50., 20., 10., 10., 10., 10.,
    100., 
    350., 350., 180., 350., 450., 450.,
    350., 350., 180., 350., 450., 450.,
  ]
  damping: [
    0.1, 0.1,
    0.5, 1.5, 0.2, 0.2, 0.2, 0.2, 0.2,
    0.5, 1.5, 0.2, 0.2, 0.2, 0.2, 0.2,
    5.0,
    7.5, 7.5, 3., 5.5, 0.5, 0.5,
    7.5, 7.5, 3., 5.5, 0.5, 0.5,
  ]
  default_qpos: [
    0.0,  0.0,
    0.25, -1.4, 0.0, -0.5, 0.0, 0.0, 0.0,
    0.25, 1.4, 0.0, 0.5, 0.0, 0.0, 0.0,
    0.0,
    -0.1, 0.0, 0.0, 0.2, -0.1, 0.0,
    -0.1, 0.0, 0.0, 0.2, -0.1, 0.0,
  ]