ROBOT_TYPE: 'unitree_inspire' # Robot type
# ROBOT_SCENE: "../roboverse/data/robots/h1_2/h1_2_27dof_with_hand.xml" # Robot scene, for Sim2Sim
ROBOT_SCENE: "../roboverse/data/robots/h1_2/motion_tracking_h1_2_27dof.xml" # Robot scene, for Sim2Sim

### REAL
DOMAIN_ID: 0 # Domain id
# Interface
INTERFACE: "en0" # Yuanhang: in simulation, lo0 for mac, lo for linux

## SIM
# DOMAIN_ID: 1 # Domain id
# # Interface
# INTERFACE: "lo0" # Yuanhang: in simulation, lo0 for mac, lo for linux

PRINT_SCENE_INFORMATION: True # Print link, joint and sensors information of robot
ENABLE_ELASTIC_BAND: True # Virtual spring band, used for lifting h1

SIMULATE_DT: 0.005  # Need to be larger than the runtime of viewer.sync()
VIEWER_DT: 0.02  # Viewer update time
USE_SENSOR: False
USE_HISTORY: False # History Hander in RL Policy

MOTOR2JOINT: [0, 1, 2, 3, 4, 5,
              6, 7, 8, 9, 10, 11,
              12, 
              13, 14, 15, 16, 17, 18, 19,
              20, 21, 22, 23, 24, 25, 26]
            
JOINT2MOTOR: [0, 1, 2, 3, 4, 5,
              6, 7, 8, 9, 10, 11,
              12, 
              13, 14, 15, 16, 17, 18, 19,
              20, 21, 22, 23, 24, 25, 26]
            

UNITREE_LEGGED_CONST:
  HIGHLEVEL: 0xEE
  LOWLEVEL: 0xFF
  TRIGERLEVEL: 0xF0
  PosStopF: 2146000000.0
  VelStopF: 16000.0
  MODE_MACHINE: 6
  MODE_PR:  0

JOINT_KP: [
    200, 200, 200, 300, 40, 40,
    200, 200, 200, 300, 40, 40,
    300, 
    120, 120, 120, 80, 80, 80, 80,
    120, 120, 120, 80, 80, 80, 80,
]


JOINT_KD: [
   2.5, 2.5, 2.5, 4.0, 2.0, 2.0,
   2.5, 2.5, 2.5, 4.0, 2.0, 2.0,
   3.0, 
   2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0,
   2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0,
]

NUM_MOTORS: 12
MOTOR_KP: [
    200, 200, 200, 300, 40, 40,
    200, 200, 200, 300, 40, 40,
    300, 
    120, 120, 120, 80, 80, 80, 80,
    120, 120, 120, 80, 80, 80, 80,
]

MOTOR_KD: [
   2.5, 2.5, 2.5, 4.0, 2.0, 2.0,
   2.5, 2.5, 2.5, 4.0, 2.0, 2.0,
   3.0, 
   2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0,
   2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0,
]

WeakMotorJointIndex:
  left_hip_yaw_joint: 0
  left_hip_roll_joint: 1
  left_hip_pitch_joint: 2
  left_knee_joint: 3
  left_ankle_pitch_joint: 4
  left_ankle_roll_joint: 5
  right_hip_yaw_joint: 6
  right_hip_roll_joint: 7
  right_hip_pitch_joint: 8
  right_knee_joint: 9
  right_ankle_pitch_joint: 10
  right_ankle_roll_joint: 11
  waist_yaw_joint : 12
  left_shoulder_pitch_joint: 13
  left_shoulder_roll_joint: 14
  left_shoulder_yaw_joint: 15
  left_elbow_joint: 16
  left_wrist_roll_joint: 17
  left_wrist_pitch_joint: 18
  left_wrist_yaw_joint: 19
  right_shoulder_pitch_joint: 20
  right_shoulder_roll_joint: 21
  right_shoulder_yaw_joint: 22
  right_elbow_joint: 23
  right_wrist_roll_joint: 24
  right_wrist_pitch_joint: 25
  right_wrist_yaw_joint: 26

NUM_MOTOR: 12
NUM_JOINTS: 12

JOINT_NAME_LIST: [
  "left_hip_yaw_joint", "left_hip_pitch_joint", "left_hip_roll_joint", "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint",
  "right_hip_yaw_joint", "right_hip_pitch_joint", "right_hip_roll_joint", "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint",
  "waist_yaw_joint",
  "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_joint", "left_wrist_roll_joint", "left_wrist_pitch_joint", "left_wrist_yaw_joint",
  "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_joint", "right_wrist_roll_joint", "right_wrist_pitch_joint", "right_wrist_yaw_joint"
]

DEFAULT_MOTOR_ANGLES: [
    0.0,  # left_hip_yaw_joint
    -0.16, # left_hip_pitch_joint
    0.0,  # left_hip_roll_joint
    0.36,  # left_knee_joint
    -0.2, # left_ankle_pitch_joint
    0.0,  # left_ankle_roll_joint

    0.0,  # right_hip_yaw_joint
    -0.16, # right_hip_pitch_joint
    0.0,  # right_hip_roll_joint
    0.36,  # right_knee_joint
    -0.2, # right_ankle_pitch_joint
    0.0,  # right_ankle_roll_joint

    0.0,  # waist_yaw_joint

    0.0,  # left_shoulder_pitch_joint
    0.0,  # left_shoulder_roll_joint
    0.0,  # left_shoulder_yaw_joint
    0.0,  # left_elbow_joint
    0.0,  # left_wrist_roll_joint
    0.0,  # left_wrist_pitch_joint
    0.0,  # left_wrist_yaw_joint

    0.0,  # right_shoulder_pitch_joint
    0.0,  # right_shoulder_roll_joint
    0.0,  # right_shoulder_yaw_joint
    0.0,  # right_elbow_joint
    0.0,  # right_wrist_roll_joint
    0.0,  # right_wrist_pitch_joint
    0.0   # right_wrist_yaw_joint
]

DEFAULT_DOF_ANGLES: [
    0.0,  # left_hip_yaw_joint
    -0.16, # left_hip_pitch_joint
    0.0,  # left_hip_roll_joint
    0.36,  # left_knee_joint
    -0.2, # left_ankle_pitch_joint
    0.0,  # left_ankle_roll_joint

    0.0,  # right_hip_yaw_joint
    -0.16, # right_hip_pitch_joint
    0.0,  # right_hip_roll_joint
    0.36,  # right_knee_joint
    -0.2, # right_ankle_pitch_joint
    0.0,  # right_ankle_roll_joint

    0.0,  # waist_yaw_joint

    0.0,  # left_shoulder_pitch_joint
    0.0,  # left_shoulder_roll_joint
    0.0,  # left_shoulder_yaw_joint
    0.0,  # left_elbow_joint
    0.0,  # left_wrist_roll_joint
    0.0,  # left_wrist_pitch_joint
    0.0,  # left_wrist_yaw_joint

    0.0,  # right_shoulder_pitch_joint
    0.0,  # right_shoulder_roll_joint
    0.0,  # right_shoulder_yaw_joint
    0.0,  # right_elbow_joint
    0.0,  # right_wrist_roll_joint
    0.0,  # right_wrist_pitch_joint
    0.0   # right_wrist_yaw_joint
]

dof_pos_lower_limit_list: [
  -0.43, -3.14, -0.43, -0.12, -0.897334, -0.261799,
  -0.43, -3.14, -3.14, -0.12, -0.897334, -0.261799,
  -2.35,
  -3.14, -0.38, -2.66, -0.95,  -3.01, -0.4625, -1.27,
  -3.14, -3.4, -3.01, -0.95, -2.75, -0.4625, -1.27
]

dof_pos_upper_limit_list: [
  0.43, 2.5, 3.14, 2.19, 0.523598, 0.261799,
  0.43, 2.5, 0.43, 2.19, 0.523598, 0.261799,
  2.35, 
  1.57, 3.4, 3.01, 3.18, 2.75, 0.4625, 1.27, 
  1.57, 0.38, 2.66, 3.18, 3.01, 0.4625, 1.27
]

dof_vel_limit_list: [
  23.0, 23.0, 23.0, 14.0, 9.0, 9.0, 
  23.0, 23.0, 23.0, 14.0, 9.0, 9.0,
  23.0, 
  9.0, 9.0, 20.0, 20.0, 31.4, 31.4, 31.4, 
  9.0, 9.0, 20.0, 20.0, 31.4, 31.4, 31.4
] 

dof_effort_limit_list: [
  200.0, 200.0, 200.0, 300.0, 60.0, 40.0, 
  200.0, 200.0, 200.0, 300.0, 60.0, 40.0,
  200.0, 
  40.0, 40.0, 18.0, 18.0, 19.0, 19.0, 19.0,
  40.0, 40.0, 18.0, 18.0, 19.0, 19.0, 19.0
]

motor_effort_limit_list: [
  200.0, 200.0, 200.0, 300.0, 60.0, 40.0, 
  200.0, 200.0, 200.0, 300.0, 60.0, 40.0,
  200.0, 
  40.0, 40.0, 18.0, 18.0, 19.0, 19.0, 19.0,
  40.0, 40.0, 18.0, 18.0, 19.0, 19.0, 19.0
]