# HYDRA_FULL_ERROR=1 python humanoidverse/train_agent.py \
# +simulator=isaacsim \
# simulator.config.cameras.enable_cameras=False \
# +exp=locomotion \
# +domain_rand=NO_domain_rand \
# +rewards=loco/reward_g1_locomotion_stairs2 \
# +robot=g1/g1_12dof \
# +terrain=terrain_locomotion_plane \
# +obs=loco/leggedloco_obs_singlestep_withlinvel_withhmap \
# +opt=wandb \
# num_envs=4096 \
# project_name=IsaacSimStairsDebug \
# experiment_name=G1_12dof_stairs_loco_with_map \
# headless=True \
# +enable_cameras=False \
# rewards.reward_penalty_curriculum=True \
# rewards.reward_initial_penalty_scale=0.1 \
# rewards.reward_penalty_degree=0.00003

# HYDRA_FULL_ERROR=1 python humanoidverse/train_agent.py \
# +simulator=isaacsim \
# simulator.config.cameras.enable_cameras=False \
# +exp=locomotion \
# +domain_rand=NO_domain_rand \
# +rewards=loco/reward_g1_locomotion_stairs2 \
# +robot=g1/g1_12dof \
# +terrain=terrain_locomotion_stairs \
# +obs=loco/leggedloco_obs_singlestep_withlinvel_withhmap \
# +opt=wandb \
# num_envs=4096 \
# project_name=IsaacSimStairsDebug \
# experiment_name=G1_12dof_stairs_loco_with_map \
# headless=True \
# +enable_cameras=True \
# rewards.reward_penalty_curriculum=True \
# rewards.reward_initial_penalty_scale=0.1 \
# rewards.reward_penalty_degree=0.00003 \
# +checkpoint=logs/IsaacSimStairsDebug/20250421_142431-G1_23dof_stairs_loco_with_map-locomotion-g1_12dof/model_700.pt

HYDRA_FULL_ERROR=1 python humanoidverse/train_agent.py \
+simulator=isaacsim \
simulator.config.cameras.enable_cameras=True \
+exp=locomotion \
+domain_rand=NO_domain_rand \
+rewards=loco/reward_g1_locomotion_stairs2 \
+robot=g1/g1_12dof \
algo=dagger_vision \
+terrain=terrain_locomotion_stairs \
+obs=loco/leggedloco_obs_singlestep_withlinvel_with_dagger_cnn \
+opt=wandb \
num_envs=2 \
project_name=IsaacSimStairsDebug \
experiment_name=G1_12dof_stairs_loco_with_depth_camera \
headless=True \
+enable_cameras=True \
algo.config.network_load_dict.teacher_actor.path=logs/IsaacSimStairsDebug/20250417_192911-G1_12dof_stairs_loco_with_map-locomotion-g1_12dof/model_2000.pt \
terrain.stairs.max_height=0.35 \
algo.config.module_dim.vision_feature_dim=128

